export const PERMISSIONS = {
  DASHBOARD_READ: 'dashboard:read',
  EMPLOYEE_READ: 'employee:read',
  EMPLOYEE_CREATE: 'employee:create',
  EMPLOYEE_UPDATE: 'employee:update',
  EMPLOYEE_DELETE: 'employee:delete',
  EMPLOYEE_MANAGE: 'employee:manage',
  ROLE_READ: 'role:read',
  ROLE_CREATE: 'role:create',
  ROLE_UPDATE: 'role:update',
  ROLE_DELETE: 'role:delete',
  PROFILE_UPDATE: 'profile:update',
  LEAD_READ: 'lead:read',
  LEAD_READ_ASSIGNED: 'lead:read_assigned',
  LEAD_CREATE: 'lead:create',
  LEAD_UPDATE: 'lead:update',
  LEAD_DELETE: 'lead:delete',
  LEAD_TRANSFER: 'lead:transfer',
  LEAD_STATUS_UPDATE: 'lead:status:update',
  LEAD_FOLLOWUP_CREATE: 'lead:followup:create',
  LEAD_NOTE_CREATE: 'lead:note:create',
  LEAD_TIMELINE_FULL: 'lead:timeline:full',
  LEAD_MASTER_MANAGE: 'lead:master:manage',
  VISIT_READ: 'visit:read',
  VISIT_READ_ASSIGNED: 'visit:read_assigned',
  VISIT_CREATE: 'visit:create',
  VISIT_UPDATE: 'visit:update',
  VISIT_FAVORITE: 'visit:favorite',
  PROPERTY_READ: 'property:read',
  PROPERTY_CREATE: 'property:create',
  PROPERTY_UPDATE: 'property:update',
  PROPERTY_DELETE: 'property:delete',
  PROPERTY_PUBLISH: 'property:publish',
  PROPERTY_MASTER_MANAGE: 'property:master:manage',
  SETTINGS_MANAGE: 'settings:manage',
  WILDCARD: '*',
} as const;

export const EMPLOYEE_LEAD_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.PROFILE_UPDATE,
  PERMISSIONS.LEAD_READ_ASSIGNED,
  PERMISSIONS.LEAD_UPDATE,
  PERMISSIONS.LEAD_STATUS_UPDATE,
  PERMISSIONS.LEAD_FOLLOWUP_CREATE,
  PERMISSIONS.LEAD_NOTE_CREATE,
  PERMISSIONS.VISIT_READ_ASSIGNED,
  PERMISSIONS.VISIT_CREATE,
  PERMISSIONS.VISIT_UPDATE,
  PERMISSIONS.VISIT_FAVORITE,
];
